name: CI
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12.0'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python Tests_and_measurements/CorrectnessTests.py